"""
Django settings for moyoguard project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v@_q-9l^&wnu^e4u7q!ho@*b3^qee-w^aqd=+%j1---lp-mhfo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'moyoweb',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'moyoguard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moyoguard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "css",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "img",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "js",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "scss",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor"/"animate.css",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor"/"swiper",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor"/"bootstrap-icons",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor"/"aos",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor" /"remixicon",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor" /"boxicons"/"css",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor" /"bootstrap"/"css",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor" /"glightbox"/"css",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor" /"isotope-layout",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor" /"bootstrap"/"js",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "vendor" /"php-email-form",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "assets" / "images" /"php-email-form",

    BASE_DIR / "moyoweb" / "templates" / "moyoweb" / "forms",
    BASE_DIR / "moyoweb" / "templates" / "moyoweb",
]

STATIC_ROOT = os.path.join(BASE_DIR, 'moyoweb' ,'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
